### PR TITLE
Add bytebin server url environment variable

### LINKED ISSUE #35: Add bytebin server host environment variable
https://github.com/lucko/spark-viewer/blob/6fc83cb0c4c478b58b08892e2351f8f3c388112f/src/SparkViewer.js#L116

### PR DESCRIPTION
**Pull request by KagurazakaNyaa**
Resolves #35 
Added environment variable `BYTEBIN_URL` to replace hardcoded bytebin server url in js file

### CODE REVIEW

**Comment by lucko** [comment]
I would prefer to do it properly 😛 

https://nextjs.org/docs/basic-features/environment-variables

**Comment by KagurazakaNyaa** [comment]
> 

I've tried using nextjs' own runtime configuration to handle this, but it doesn't work.
https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration
https://github.com/vercel/next.js/discussions/17197
https://github.com/vercel/next.js/discussions/34894
At the same time, it does not take effect directly through `getInitialProps` or `getServerSideProps`, it seems that there should be a problem with nextjs itself.
https://github.com/vercel/next.js/issues/41638

**Comment by TheDevMinerTV** [comment]
I've rebuilt the changes done here but using the normal environment variables (and it works).

**Comment by KagurazakaNyaa** [comment]
#62 looks like a more elegant implementation, this PR is no longer valid.

**Pull request closed without merging**
